---
#-------------------------------
# General Site Settings
title: EAM
logo: logo_eam.svg # You can add own logo.
description: Blog Pessoal de Elissandro Mendes

#-------------------------------
# Author Settings
author:
  name: Elissandro Mendes
  image: 01.jpg
  say-hello: Hello, I’m <strong>Elissandro Mendes</strong>
  bio: <strong>Pessoa desenvolvedora</strong>, apaixonado por Física e Ciências em geral, cientista de dados em formação, entusiasta do aprendizado de máquina. Espaço criado para compartilhar aprendizados, tutorias e opiniões.

#-------------------------------
# Contact links
twitter: https://twitter.com/elissandroam/ # Add your Twitter handle
facebook: https://www.facebook.com/elissandro.mendes/ # Add your Facebook handle
# dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram: https://www.instagram.com/elissandroam/ # Add your Instagram handle
# pinterest: https://pinterest.com/ # Add your Pinterest handle

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: elissandroam # Add instagram username

#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.

#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
